### ISSUE TITLE
Make Dockerfile compliant with Azure DevOps guidelines

### ISSUE THREAD

**Issue by dennis-sig** [Software-Improvement-Group/sigridci#131]
See https://learn.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops&tabs=yaml#linux-based-containers. 

- [ ] Bash
- [ ] glibc-based
- [ ] Can run Node.js (which the agent provides)
- [ ] Does not define an ENTRYPOINT
- [ ] USER has access to groupadd and other privileges commands without sudo

Unfortunately we are one of the "extremely stripped-down containers" based on Alpine Linux the documentation refers to. This is intentional, as it keeps the container as lightweight as possible. We would prefer to avoid having a separate Dockerfile for each platform, but their requirements regarding NodeJS and Bash might make this difficult. 

@patveck What is your opinion?

**Comment by patveck** [comment]
We currently use `python:3.10-alpine` as base image, which doesn't meet (and probably never will meet) the second requirement. I propose we try `python:3.10-slim`, which uses Debian as its base image (so GLibC-based AFAIK) and is still quite small (about 45 MB). If that doesn't meet all 5 requirements, we can simply use `python:3.10`, which is a lot larger but still manageable. I think that in practice, the image is typically cached in the runner's local container store anyway.
