### ISSUE TITLE
Specifying a quality target

### ISSUE THREAD

**Issue by JohanVT** [Software-Improvement-Group/sigridci#136]
From the documentation of "[Specifying a quality target](https://github.com/Software-Improvement-Group/sigridci/blob/main/docs/client-script-usage.md#specifying-a-quality-target)" it is not really clear to me how setting the quality target values in `sigrid.yaml` interacts with the --targetquality flag passed (or not passed) to the `sigridci.py` script. Suggestion: add that information to the documentation.

**Comment by dennis-sig** [comment]
Hi @JohanVT! There are now *three* different options for [defining quality targets](https://github.com/Software-Improvement-Group/sigridci/blob/main/docs/client-script-usage.md):

- We now also allow people to define goals in Sigrid, so the new default for Sigrid CI is to use whatever target was defined in Sigrid. 
- For backward compatibility, we still allow people to set a custom target for Sigrid CI using the `—targetquality` option. This is no longer the default, so we removed this option from all of the examples. That also makes the examples a bit simpler, i.e. using the target from Sigrid is more obvious as default behavior.
- The per-metric targets are *in addition* to the overall target. We wouldn't recommend this for the typical case as it's more in the direction of micro-managing quality, but there are some cases where people really want to set specific targets for specific metrics.

**Comment by JohanVT** [comment]
Thanks for updating the examples!
