### ISSUE TITLE
Specifying quality targets per metric

### ISSUE THREAD

**Issue by janlaan** [Software-Improvement-Group/sigridci#158]
We may want to have different targets per metric. Having these allow you to more targeted goals. 
Example usecases:
- You care less about duplication because it's a microservice environment. 
- You really care about duplication, it's the bane of your existence. You already have a 5 star rating for Duplication and want to keep it that way.
- There's (temporary) issues with how Sigrid measures module coupling for your technology, leading to too much failed CI checks. You can't work like that.

Kinda related to #135 which also asks for more targeted targets, but for technologies instead of metrics

**Comment by Geertien** [comment]
@janlaan, what is the difference between this request and the existing functionality described in https://github.com/Software-Improvement-Group/sigridci/blob/main/docs/client-script-usage.md#option-3-advanced-per-metric-targets?

**Comment by janlaan** [comment]
The difference is that I didn't see that page. I guess I got lost in all the documentation/features. Thanks!
