### ISSUE TITLE
No built-in way to clean up the zipfile

### ISSUE THREAD

**Issue by nicorikken** [Software-Improvement-Group/sigridci#164]
The script leaves the .zip file in place that is a mere implementation detail for handling the upload. I'm of the opinion that the zip file has to be removed by default or at least by providing a flag.

The lack of zip file removal is an issue if you run this command multiple times in a persistent environment. Then one has to use other means to clean up those zipfiles.

A way towards a solution might be to use `tempfile` and create a `tempfile.TemporaryDirectory`, store the zip file there and remove it afterwards using `cleanup()`. Or rather than creating a directory one can also create a temporary file.

**Comment by dennis-sig** [comment]
@nicorikken Thanks, and agree with your suggestion. In the beginning we intentionally left the ZIP so that people can inspect the contents of the ZIP during troubleshooting, but we added an option to show the ZIP contents ages ago. So there is indeed no more argument to litter ZIP files everywhere.

**Comment by dennis-sig** [comment]
Closing this one after we merged https://github.com/Software-Improvement-Group/sigridci/pull/165.

**Comment by MichielCuijpers** [comment]
@nicorikken we needed to revert #165 because of a permission problem on windows. We will find a new way to clean up the zip files. cc @dennis-sig @Geertien
