### ISSUE TITLE
Mailcap is deprecated in newest Python version (3.13)

### ISSUE THREAD

**Issue by RoySp** [Software-Improvement-Group/sigridci#560]
When using python 3.13 (last release) there is an issue with the removal of the Mailcap library.
Yesterday pull request [555](https://github.com/Software-Improvement-Group/sigridci/pull/555) is approved. In this pull request there is a new import in report.py that uses this library.  

When executing Sigrid CI on python 3.13 you will receive a error "No module named 'mailcap'".

Mailcap is deprecated since pyton version 3.11 and completely removed in version 3.13.

https://docs.python.org/3.13/library/mailcap.html

https://github.com/Software-Improvement-Group/sigridci/blob/61f61d17517a44745f2df8a3d1ec92d73e27a1ef/sigridci/sigridci/reports/report.py#L17

**Comment by dennis-sig** [comment]
Thanks Roy! We haven't heard about this yet, probably because our Docker container is on Python 3.11. The import is unused, so we'll fix it right away.

**Comment by MichielCuijpers** [comment]
@dennis-sig that was quick!
thanks @RoySp  we can not make it nicer, be we can make it better ;-)
